### ISSUE TITLE
Don't remove all callback at the end of the tour

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-wui-toolkit#136]
Why do you remove all call back at the end of the tour ?
The callback are called just a the first time....

https://github.com/gisaia/ARLAS-wui-toolkit/blob/e76a3512dd4a3f3f47f1f4996ac9cb3c7675f736/src/app/services/walkthrough/walkthrough.service.ts#L74-L81

**Comment by sebbousquet** [comment]
Callbacks are removed to avoid a double call of `next` event, if you restart the tour.

```javascript
this.hopscotch.listen('next', () => {
    localStorage.setItem(this.tourData.id, this.hopscotch.getCurrStepNum());
});
```
