### ISSUE TITLE
Network Error when accessing Arlas GUI

### ISSUE THREAD

**Issue by brunofigueres** [gisaia/ARLAS-wui-toolkit#589]
I have  a fresh new install of Arlas WUI.
When I try to connect to it I've got a message:
Error
NetworkError when attempting to fetch resource.
Origin
ARLAS-wui runtime: an error occured while updating the configuration. Code: 001
What to do
Please feel free to create an issue in "https://github.com/gisaia/ARLAS-wui-toolkit/issues"
Error
TypeError: NetworkError when attempting to fetch resource.
Origin
ARLAS-wui runtime
What to do

Tested on Firefox 101 and 105 versions. In chrome or chromium the GUI does not display but no error messages.

**Comment by MohamedHamouGisaia** [comment]
Hello @brunofigueres, 

Sorry for the late answer;

How did you start your ARLAS stack ? Did you use the start.sh script in [ARLAS-Exploration-stack](https://github.com/gisaia/ARLAS-Exploration-stack) project ? or did you start ARLAS-wui in dev mode ?

**Comment by mbarbet** [comment]
Viewed with the dev team, the problem is fixed
