### ISSUE TITLE
Bookmarks store all collections

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui-toolkit#657]
When creating a bookmark, the collections field is a string concatenating all the collections that are in the workspace, including some that are not in the dashboard. This makes bookmarks available made in a dashboard with X collection, available in a dashboard with Y and Z collections.

**Comment by MohamedHamouGisaia** [comment]
HAs been fixed by @mbarbet in [this PR](https://github.com/gisaia/ARLAS-wui-toolkit/pulls)
